version: "3.8"

volumes:
  rabbitmq_data:

services:
  ####################################
  # RabbitMQ: The messaging broker
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  ###################################
  # Profile: The Profile microservice
  ###################################
  profile:
    build:
      context: ./
      dockerfile: profile.Dockerfile
    image: jzshum/profile:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/profile
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  ###################################
  # Funds: The Funds microservice
  ###################################
  funds:
    build:
      context: ./
      dockerfile: funds.Dockerfile
    image: jzshum/funds:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/funds
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
      
  ###################################
  # Portfolio: The Portfolio microservice
  ###################################
  portfolio:
    build:
      context: ./
      dockerfile: portfolio.Dockerfile
    image: jzshum/portfolio:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/portfolio
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"

  #################################################
  # Authenticate User: The Authenticate User microservice
  #################################################
  auth_user:
    build:
      context: ./
      dockerfile: auth_user.Dockerfile
    image: jzshum/auth_user:esd
    restart: always
    depends_on:
      - funds
      - profile
    environment:
      profile_URL: http://portfolio:5003/profile
      funds_URL: http://funds:5002/funds
      PYTHONUNBUFFERED: 1
    ports:
      - "5200:5200"

  #################################################
  # Yahoo Friend: The Yahoo Friend microservice
  #################################################
  yahoo_friend:
    build:
      context: ./
      dockerfile: yahoo_friend.Dockerfile
    image: jzshum/yahoo_friend:esd
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5900:5900"

  #################################################
  # Activity Log: The Activity Log microservice
  #################################################
  activity_log:
    build:
      context: ./
      dockerfile: activity_log.Dockerfile
    image: jzshum/activity_log:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: jzshum/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###############################################
  # Order Management: The Order Management microservice
  ###############################################
  order_management:
    build:
      context: ./
      dockerfile: order_management.Dockerfile
    image: jzshum/order_management:esd
    restart: always
    depends_on:
      - funds
      - portfolio
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      portfolio_URL: http://portfolio:5001/portfolio
      funds_URL: http://funds:5002/funds
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ###############################################
  # User Profile: The User Profile microservice
  ###############################################
  user_profile:
    build:
      context: ./
      dockerfile: userprofile.Dockerfile
    image: jzshum/userprofile:esd
    restart: always
    depends_on:
      - funds
      - portfolio
      - profile
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      portfolio_URL: http://portfolio:5001/portfolio
      funds_URL: http://funds:5002/funds
      profile_URL: http://profile:5003/profile
      PYTHONUNBUFFERED: 1
    ports:
      - "5008:5008"